apiVersion: v1
kind: Service
metadata:
  name: cs-application-test
spec:
  type: NodePort
  selector:
    app: cs-application-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000